Network:
  physical_batch_size: 5
#  physical_batch_size: 16
  lr: 5e-5
  weight_decay: 0
  amsgrad: False
  num_epochs: 1000
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
DP_checkpoint_name: DP_checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /home/soroosh/Documents/datasets/XRay/
target_dir: /home/soroosh/Documents/Repositories_target_files/DP_CXR/
display_stats_freq: 1 # valid freq is equal to this
#display_stats_freq: 15 # valid freq is equal to this

DP:
  epsilon: 70
#  delta: 1e-6  # [for full UKA] at least inverse of the training dataset length, or lower
  delta: 1e-4  # [for 5K UKA] at least inverse of the training dataset length, or lower
  max_grad_norm: 1.0 # this has a direct relationship with controling the sensitivity
  noise_multiplier: 0.5 # usually between [0.1 , 2]
  logical_batch_size: 15 # for physical of 5
#  logical_batch_size: 64 # for physical of 16
