Network:
  batch_size: 5
#  batch_size: 16
  lr: 5e-5
  weight_decay: 0
  amsgrad: False
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /home/soroosh/Documents/datasets/XRay/
target_dir: /home/soroosh/Documents/Repositories_target_files/DP_CXR/
network_save_freq: 2 # number of epochs to save
display_stats_freq: 1 # valid freq is equal to this
num_epochs: 1000

DP:
  epsilon: 10
  delta: 5e-6  # at least inverse of the training dataset length, or lower
  max_grad_norm: 1.2
  logical_batch_size: 15
#  logical_batch_size: 64
