Network:
  physical_batch_size: 32
  lr: 2e-4
  weight_decay: 0
  num_epochs: 100
network_output_path: network_data/
output_data_path: output_data/
tb_logs_path: tensor_board_logs/
stat_log_path: stat_logs
checkpoint_name: checkpoint.tar
DP_checkpoint_name: DP_checkpoint.tar
trained_model_name: trained_model.pth

# changeable items:
file_path: /PATH TO DATASET/
target_dir: /WHERE YOU WANT TO STORE YOUR EXPERIMENTS/
display_stats_freq: 1 # valid freq is equal to this

DP:
  epsilon: 1
  delta: 1e-6  # [for full UKA] at least inverse of the training dataset length, or lower
  max_grad_norm: 1.5 # this has a direct relationship with controlling the sensitivity
  logical_batch_size: 128 # for physical of 32
